---
- name: Add docker repo
  copy: src=files/docker.repo dest=/etc/yum.repos.d/docker.repo

- name: upgrade all packages
  yum: name=* state=latest
  register: installed
  until: installed|success
  retries: 5
  delay: 30


- name: Install deps
  yum: name={{item}} state=latest
  with_items:
    - python
    - python-devel
    - python-pip
    - libselinux-python
    - docker-engine

- name: Creates docker images dir
  file: path={{docker_storage}} state=directory

- name: add DOCKER_OPTS for storage
  template: src=templates/docker.j2 dest={{ default_conf }}

- name: add docker service file
  template: src=templates/docker.service.j2 dest={{ docker_service_file }}


- name: Install docker compose from daocloud
  get_url: url=https://get.daocloud.io/docker/compose/releases/download/1.5.1/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose

- command: chmod +x /usr/local/bin/docker-compose

- name: Reload systemctl
  command: systemctl daemon-reload

- name: Restart docker
  service: name=docker state=restarted

- name: Download dao
  get_url: url=https://get.daocloud.io/daomonit/daomonit.x86_64.rpm dest=/tmp/daomonit.x86_64.rpm

- name: Install dao
  yum: name=/tmp/daomonit.x86_64.rpm state=present

- name: Config dao
  command: "daomonit -token=bd795efc7616216c0b465013344685c3c96588a2 save-config"

- name: Start dao service
  service: name=daomonit state=started

- name: add docker0 to trusted zone
  command: firewall-cmd --zone=trusted --add-interface=docker0 --permanent
- command: firewall-cmd --zone=trusted --add-interface=docker0

- name: Restart firewalld
  service: name=firewalld state=restarted

- name: Restart docker
  service: name=docker state=restarted

- name: Creates local facts dir
  file: path=/etc/ansible/facts.d state=directory

- name: Install docker fact
  copy: content="{{ docker_info }}" dest=/etc/ansible/facts.d/docker.fact
